### ISSUE TITLE
using CI to build PDFs with all images

### ISSUE THREAD

**Issue by GuilhermeHideki** [jstpcs/lnxpcs#21]
Since you were interested in https://github.com/jstpcs/lnxpcs/pull/20,
I think it would be a good idea if you added a TravisCI, or similar thing, to create a PDF
when you push to master, or add a new tag/release.

**Comment by jstpcs** [comment]
I uploaded the categorized previews of all images to [linux.pictures](https://linux.pictures/). I think that everyone can clone the repo/folder and build the pdf with the desired pictures from command line. Do you think that there is a need of automatic rebuilding the PDF after every push?

**Comment by peterdemin** [comment]
Actually, I made a PDF in #20 specifically to have it printed multiple per sheet. Because I wanted to have it in credit-card size. Turned out, I had to do a lot of cutting after, because of uneven margins.
What I think would be great, if prebuilt PDF would have zero margins, so cards could be done with fewer cuts.
But that requires much more effort, than running `convert`.

**Comment by GuilhermeHideki** [comment]
I don't see a *need* now, it's more like *why not / coolness*.
