### ISSUE TITLE
Hard to order from "International" (costs) and copyright "worries" from print shops

### ISSUE THREAD

**Issue by jrie** [jstpcs/lnxpcs#42]
Hello, thanks for the collections!

I would like to order several pieces through the links offered, but international shipping seems to be very expensive through the provided links.

Therefore I would like to ask for other providers, for example one located in Europe, which does not have the high delivery costs or limited sales offers. For a permanent supply!

Also as a note, I downloaded some of the graphics and made vectors (.svg) of some of them in order to get them printed at "Spreadshirt" (its a german supplier) and they had worries about copyright infringement or abuse of the "logos" like "Gitbub - The place where i fork".

In order to avoid such things, I would like to clarify, for example through a special "legal.md" which can be linked to clarify the last issue, which states that the material can be used as "is" without worrying about abuse or copyright issues - or something related.

I noticed this only by one supplier, but this was very frustrating as there is no way to explain, that this is "legal"... and no one needs to worry. I was missing out some arguments.

**Comment by jstpcs** [comment]
hi, you are free to download any pic and make an order at local store to save some money, it's completely ok. the images are made for fun and without any intention to make profit from them. if any image is claimed to violate some rules, we'll remove it immediately as we are for fair play and respect the rules. if you are in europe, theare are dozens of alternatives to spreadshirt. and please keep in mind that pics are distributed in png because sharing in vector (svg) violates the license for stock images that are used in some of them. sure, if someone decides to trace them for personal purposes and keeps in secret, no one tells him anything ;)
