### ISSUE TITLE
.svg?

### ISSUE THREAD

**Issue by philer** [jstpcs/lnxpcs#8]
Those cards look like vector graphics, would it be possible to make them available as .svg files?

Either way great work!
Cheers

**Comment by jstpcs** [comment]
For some images stock graphics that can't be shared in vector format is used. But if the hi-res that is provided is not enough for your purpose, contact me via [email](mailto:jstpcs@ya.ru) I can try to make a bigger one for you. The same is if you need something with transparent background.

**Comment by nightsh** [comment]
@philer even though this issue is closed, since I came here looking for the same thing (?) I might as well share my experience.

I imagine you want transparent background on some, so you can print them on differently colored materials, right? In my experience, having them imported in GIMP or anything similar and doing a color replacement on the background is working just fine.

As for vector format, there's a use case for that @jstpcs, and that is vynil cutting. Thankfully, you did awesome high res images of all of them, so if such a thing is *really* needed, most of them can be easily converted to vector using Inkscape or any other software capable of doing that.

I'm leaving this note here for anyone who might come looking for the same stuff.

Also last but not least, many thanks for creating what is easily the best looking collection of free software related artwork. Kudos!
